# Generated by Django 4.2.27 on 2026-01-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
