# Generated by Django 4.2.27 on 2026-01-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
