# Generated by Django 4.2.27 on 2026-01-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incident_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
