# Generated by Django 4.2.27 on 2026-01-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.department'),
        ),
    ]
