# Generated by Django 4.2.27 on 2026-01-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_alter_incident_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
