# Generated by Django 4.2.27 on 2026-01-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_alter_incident_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='department',
        ),
    ]
