# Generated by Django 4.2.27 on 2026-01-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_department_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_to_department',
            field=models.BooleanField(default=False),
        ),
    ]
