# Generated by Django 4.2.27 on 2026-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_incident_reported_at_incident_reported_to_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
