# Generated by Django 4.2.27 on 2026-02-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_otp_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_otp_created_at',
        ),
    ]
