# Generated by Django 4.2.27 on 2026-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0020_incident_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='email_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
